# -*- coding: utf-8 -*-
"""Embarcación

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqaWPzMHoEusI_9iUqs1e961XgJvAYVj
"""

class Embarcacion:
    def __init__(self, matricula, nombre, eslora, manga, anioConstruccion,respuesta, numeroMastiles, numeroCamarotes, capacidadPasajeros,tipoVela, tipoCasco, potenciaMotor, velocidadMaxima, tieneHelipuerto):
        self.matricula = matricula
        self.nombre = nombre
        self.eslora = eslora
        self.manga = manga
        self.anioConstruccion = anioConstruccion
        self.respuesta = respuesta
        self.numeroMastiles = numeroMastiles
        self.numeroCamarotes = numeroCamarotes
        self.capacidadPasajeros = capacidadPasajeros
        self.tipoVela = tipoVela
        self.tipoCasco = tipoCasco
        self.potenciaMotor = potenciaMotor
        self.velocidadMaxima = velocidadMaxima
        self.tieneHelipuerto = tieneHelipuerto

        print("\nHola, qué tal")
        print("Mi nombre es John y esta es mi central de embarcaciones, tengo bastantes barcos aquí\n")

    def navegar(self):
        print("\nEl bote ya está listo, es hora de NAVEGAR!!!")

    def navegando(self):
        print("Estamos en aguas internacionales, hay que tener cuidado")

    def atracar(self):
        print("Tengan cuidado, la marina está en la orilla, VENDRÁN A ATRACAR NUESTRO BOTE!!!")

    def policiaAtrapada(self):
        print("Nos atrapó la marina, VERDI, BORRA MI HISTORIAL DE GOOGLE!!!")

    def izarVelas(self):
        print("La marina nos sigue, iza las velas, RÁPIDO!!!")

    def activarMotor(self):
        print("Mi yate ya está limpio, solo activa el motor y vamonos")

    def acelerar(self):
        print("La lancha tiene mucha potencia, sigue acelerando que aún nos sigue la marina!!!")

    def helipuerto(self):
        if self.tieneHelipuerto:
            print("Sí, hay un helipuerto cerca de la costa")
        else:
            print("No, ahora vete de aquí, ¡RÁPIDO!")

    # ---------- Métodos para mostrar información ----------
    def mostrarInfoVelero(self):
        print("\n***** Información Velero *****")
        print("\nMatricula: ", self.matricula,"\nNombre: ",self.nombre,"\nTamaño de eslora: ",self.eslora,"\nTamaño de manga: ",self.manga,"\nAño de construcción: ",self.anioConstruccion,"\Cantidad de mastiles: ",self.mastiles)
        print("*******************************")

    def mostrarInfoYate(self):
        print("\n***** Información Yate *****")
        print("\nMatricula: ", self.matricula, "\nNombre: ", self.nombre, "\nTamaño de eslora: ", self.eslora,"\nTamaño de manga: ", self.manga, "\nAño de construcción: ", self.anioConstruccion,"\nCantidad de camarotes: ",self.numeroCamarotes,"Tiene helipuerto?: ",self.tieneHelipuerto)
        print("*******************************")

    def mostrarInfoLancha(self):
        print("\n***** Información Lancha *****")
        print("\nMatricula: ", self.matricula, "\nNombre: ", self.nombre, "\nTamaño de eslora: ", self.eslora,"\nTamaño de manga: ", self.manga, "\nAño de construcción: ", self.anioConstruccion,"\nCapacidad de pasajeros: ",self.capacidadPasajeros,"\nCasco de la lancha: ",self.tipoCasco,"\nVelocidad máxima de la lancha: ",self.velocidadMaxima)
        print("*******************************")

    def __del__(self):
        print("\nYa nos atrapó la policía, lo siento amigos\n")

print("\n***** Registro del Velero *****\n")
matriculaVelero = input("Cuál es la matrícula de su velero?: ")
nombreVelero = input("Cuál es el nombre que le puso a su velero?: ")
esloraVelero = float(input("Cuánto mide la eslora de su velero en metros?: "))
mangaVelero = float(input("Cuánto mide la manga de su velero en metros?: "))
anioConstruccionVelero = int(input("En qué año se construyó su velero?: "))
mastilesVelero = int(input("Cuántos mástiles tiene su velero?: "))
tipoVelaVelero = input("Cómo son las velas que tiene su velero?: ")

velero = Embarcacion(
    matricula=matriculaVelero,
    nombre=nombreVelero,
    eslora=esloraVelero,
    manga=mangaVelero,
    anioConstruccion=anioConstruccionVelero,
    numeroMastiles=mastilesVelero,
    tipoVela=tipoVelaVelero
)
velero.navegar()
velero.navegando()
velero.atracar()
velero.izarVelas()
velero.policiaAtrapada()
velero.mostrarInfoVelero()

print("\n***** Registro del Yate *****\n")
matriculaYate = input("Cuál es la matrícula de su yate?: ")
nombreYate = input("Cuál es el nombre que le puso a su yate?: ")
esloraYate = float(input("Cuánto mide la eslora de su yate en metros?: "))
mangaYate = float(input("Cuánto mide la manga de su yate en metros?: "))
anioConstruccionYate = int(input("En qué año se construyó su yate?: "))
numeroCamarotesYate = int(input("Cuántas habitaciones tiene su yate?: "))
respuesta = input("Tiene un helipuerto donde estacionar su yate? (si/no): ")
tieneHelipuertoYate = respuesta.lower() == "si"

yate = Embarcacion(
    matricula=matriculaYate,
    nombre=nombreYate,
    eslora=esloraYate,
    manga=mangaYate,
    anioConstruccion=anioConstruccionYate,
    numeroCamarotes=numeroCamarotesYate,
    tieneHelipuerto=tieneHelipuertoYate
)
yate.navegar()
yate.activarMotor()
yate.navegando()
yate.atracar()
yate.policiaAtrapada()
yate.mostrarInfoYate()

print("\n***** Registro de la Lancha *****\n")
matriculaLancha = input("Cuál es la matrícula de su lancha?: ")
nombreLancha = input("Cuál es el nombre que le puso a su lancha?: ")
esloraLancha = float(input("Cuánto mide la eslora de su lancha en metros?: "))
mangaLancha = float(input("Cuánto mide la manga de su lancha en metros?: "))
anioConstruccionLancha = int(input("En qué año se construyó su lancha?: "))
capacidadPasajerosLancha = int(input("Cuántos pasajeros pueden haber en su lancha?: "))
tipoCascoLancha = input("Cómo es el casco de su lancha?: ")
velocidadMaximaLancha = float(input("Cuál es la velocidad máxima a la que puede ir su lancha?: "))

lancha = Embarcacion(
    matricula=matriculaLancha,
    nombre=nombreLancha,
    eslora=esloraLancha,
    manga=mangaLancha,
    anioConstruccion=anioConstruccionLancha,
    capacidadPasajeros=capacidadPasajerosLancha,
    tipoCasco=tipoCascoLancha,
    velocidadMaxima=velocidadMaximaLancha
)
lancha.navegar()
lancha.navegando()
lancha.atracar()
lancha.acelerar()
lancha.policiaAtrapada()
lancha.mostrarInfoLancha()